// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/agent/agent.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/agent/agent.go -destination=internal/mocks/mock_agent_repo.go -package=mocks -mock_names=Repository=MockAgentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/alanyang/agent-mesh/internal/domain/agent"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRepository is a mock of Repository interface.
type MockAgentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRepositoryMockRecorder
	isgomock struct{}
}

// MockAgentRepositoryMockRecorder is the mock recorder for MockAgentRepository.
type MockAgentRepositoryMockRecorder struct {
	mock *MockAgentRepository
}

// NewMockAgentRepository creates a new mock instance.
func NewMockAgentRepository(ctrl *gomock.Controller) *MockAgentRepository {
	mock := &MockAgentRepository{ctrl: ctrl}
	mock.recorder = &MockAgentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRepository) EXPECT() *MockAgentRepositoryMockRecorder {
	return m.recorder
}

// ClaimAgent mocks base method.
func (m *MockAgentRepository) ClaimAgent(ctx context.Context, projectID uuid.UUID, role string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimAgent", ctx, projectID, role)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimAgent indicates an expected call of ClaimAgent.
func (mr *MockAgentRepositoryMockRecorder) ClaimAgent(ctx, projectID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimAgent", reflect.TypeOf((*MockAgentRepository)(nil).ClaimAgent), ctx, projectID, role)
}

// Create mocks base method.
func (m *MockAgentRepository) Create(ctx context.Context, a agent.Agent) (agent.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(agent.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentRepository)(nil).Create), ctx, a)
}

// GetByID mocks base method.
func (m *MockAgentRepository) GetByID(ctx context.Context, id uuid.UUID) (agent.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(agent.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAgentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAgentRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAgentRepository) List(ctx context.Context, filters agent.ListFilters) ([]agent.Agent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]agent.Agent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAgentRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAgentRepository)(nil).List), ctx, filters)
}

// ListOfflineWithInflightTasks mocks base method.
func (m *MockAgentRepository) ListOfflineWithInflightTasks(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOfflineWithInflightTasks", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOfflineWithInflightTasks indicates an expected call of ListOfflineWithInflightTasks.
func (mr *MockAgentRepositoryMockRecorder) ListOfflineWithInflightTasks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOfflineWithInflightTasks", reflect.TypeOf((*MockAgentRepository)(nil).ListOfflineWithInflightTasks), ctx)
}

// SetIdleStatus mocks base method.
func (m *MockAgentRepository) SetIdleStatus(ctx context.Context, agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIdleStatus", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIdleStatus indicates an expected call of SetIdleStatus.
func (mr *MockAgentRepositoryMockRecorder) SetIdleStatus(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIdleStatus", reflect.TypeOf((*MockAgentRepository)(nil).SetIdleStatus), ctx, agentID)
}

// SetWorkingStatus mocks base method.
func (m *MockAgentRepository) SetWorkingStatus(ctx context.Context, agentID, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkingStatus", ctx, agentID, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkingStatus indicates an expected call of SetWorkingStatus.
func (mr *MockAgentRepositoryMockRecorder) SetWorkingStatus(ctx, agentID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkingStatus", reflect.TypeOf((*MockAgentRepository)(nil).SetWorkingStatus), ctx, agentID, taskID)
}

// UpdateStatus mocks base method.
func (m *MockAgentRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status agent.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockAgentRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockAgentRepository)(nil).UpdateStatus), ctx, id, status)
}
