// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/thread/thread.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/thread/thread.go -destination=internal/mocks/mock_thread_repo.go -package=mocks -mock_names=Repository=MockThreadRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	thread "github.com/alanyang/agent-mesh/internal/domain/thread"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockThreadRepository is a mock of Repository interface.
type MockThreadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThreadRepositoryMockRecorder
	isgomock struct{}
}

// MockThreadRepositoryMockRecorder is the mock recorder for MockThreadRepository.
type MockThreadRepositoryMockRecorder struct {
	mock *MockThreadRepository
}

// NewMockThreadRepository creates a new mock instance.
func NewMockThreadRepository(ctrl *gomock.Controller) *MockThreadRepository {
	mock := &MockThreadRepository{ctrl: ctrl}
	mock.recorder = &MockThreadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadRepository) EXPECT() *MockThreadRepositoryMockRecorder {
	return m.recorder
}

// CreateMessage mocks base method.
func (m_2 *MockThreadRepository) CreateMessage(ctx context.Context, m thread.Message) (thread.Message, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CreateMessage", ctx, m)
	ret0, _ := ret[0].(thread.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockThreadRepositoryMockRecorder) CreateMessage(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockThreadRepository)(nil).CreateMessage), ctx, m)
}

// CreateThread mocks base method.
func (m *MockThreadRepository) CreateThread(ctx context.Context, t thread.Thread) (thread.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThread", ctx, t)
	ret0, _ := ret[0].(thread.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateThread indicates an expected call of CreateThread.
func (mr *MockThreadRepositoryMockRecorder) CreateThread(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThread", reflect.TypeOf((*MockThreadRepository)(nil).CreateThread), ctx, t)
}

// GetThreadByID mocks base method.
func (m *MockThreadRepository) GetThreadByID(ctx context.Context, id uuid.UUID) (thread.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadByID", ctx, id)
	ret0, _ := ret[0].(thread.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadByID indicates an expected call of GetThreadByID.
func (mr *MockThreadRepositoryMockRecorder) GetThreadByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadByID", reflect.TypeOf((*MockThreadRepository)(nil).GetThreadByID), ctx, id)
}

// ListMessages mocks base method.
func (m *MockThreadRepository) ListMessages(ctx context.Context, threadID uuid.UUID) ([]thread.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, threadID)
	ret0, _ := ret[0].([]thread.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockThreadRepositoryMockRecorder) ListMessages(ctx, threadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockThreadRepository)(nil).ListMessages), ctx, threadID)
}

// ListThreads mocks base method.
func (m *MockThreadRepository) ListThreads(ctx context.Context, filters thread.ListFilters) ([]thread.Thread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThreads", ctx, filters)
	ret0, _ := ret[0].([]thread.Thread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThreads indicates an expected call of ListThreads.
func (mr *MockThreadRepositoryMockRecorder) ListThreads(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThreads", reflect.TypeOf((*MockThreadRepository)(nil).ListThreads), ctx, filters)
}
