// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/prompt/prompt.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/prompt/prompt.go -destination=internal/mocks/mock_prompt_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	prompt "github.com/alanyang/agent-mesh/internal/domain/prompt"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPromptRepository is a mock of PromptRepository interface.
type MockPromptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPromptRepositoryMockRecorder
	isgomock struct{}
}

// MockPromptRepositoryMockRecorder is the mock recorder for MockPromptRepository.
type MockPromptRepositoryMockRecorder struct {
	mock *MockPromptRepository
}

// NewMockPromptRepository creates a new mock instance.
func NewMockPromptRepository(ctrl *gomock.Controller) *MockPromptRepository {
	mock := &MockPromptRepository{ctrl: ctrl}
	mock.recorder = &MockPromptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromptRepository) EXPECT() *MockPromptRepositoryMockRecorder {
	return m.recorder
}

// GetForRole mocks base method.
func (m *MockPromptRepository) GetForRole(ctx context.Context, projectID *uuid.UUID, role string) (prompt.RolePrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForRole", ctx, projectID, role)
	ret0, _ := ret[0].(prompt.RolePrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForRole indicates an expected call of GetForRole.
func (mr *MockPromptRepositoryMockRecorder) GetForRole(ctx, projectID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForRole", reflect.TypeOf((*MockPromptRepository)(nil).GetForRole), ctx, projectID, role)
}

// List mocks base method.
func (m *MockPromptRepository) List(ctx context.Context, projectID uuid.UUID) ([]prompt.RolePrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]prompt.RolePrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPromptRepositoryMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPromptRepository)(nil).List), ctx, projectID)
}

// Set mocks base method.
func (m *MockPromptRepository) Set(ctx context.Context, p prompt.RolePrompt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPromptRepositoryMockRecorder) Set(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPromptRepository)(nil).Set), ctx, p)
}
