// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/task/task.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/task/task.go -destination=internal/mocks/mock_task_repo.go -package=mocks -mock_names=Repository=MockTaskRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	task "github.com/alanyang/agent-mesh/internal/domain/task"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskRepository is a mock of Repository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
	isgomock struct{}
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// AddDependency mocks base method.
func (m *MockTaskRepository) AddDependency(ctx context.Context, dep task.Dependency) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDependency", ctx, dep)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDependency indicates an expected call of AddDependency.
func (mr *MockTaskRepositoryMockRecorder) AddDependency(ctx, dep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDependency", reflect.TypeOf((*MockTaskRepository)(nil).AddDependency), ctx, dep)
}

// Assign mocks base method.
func (m *MockTaskRepository) Assign(ctx context.Context, taskID, agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, taskID, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockTaskRepositoryMockRecorder) Assign(ctx, taskID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockTaskRepository)(nil).Assign), ctx, taskID, agentID)
}

// AssignIfIdle mocks base method.
func (m *MockTaskRepository) AssignIfIdle(ctx context.Context, taskID, agentID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignIfIdle", ctx, taskID, agentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignIfIdle indicates an expected call of AssignIfIdle.
func (mr *MockTaskRepositoryMockRecorder) AssignIfIdle(ctx, taskID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignIfIdle", reflect.TypeOf((*MockTaskRepository)(nil).AssignIfIdle), ctx, taskID, agentID)
}

// Create mocks base method.
func (m *MockTaskRepository) Create(ctx context.Context, t task.Task) (task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskRepository)(nil).Create), ctx, t)
}

// GetByID mocks base method.
func (m *MockTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTaskRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTaskRepository)(nil).GetByID), ctx, id)
}

// GetDependencies mocks base method.
func (m *MockTaskRepository) GetDependencies(ctx context.Context, taskID uuid.UUID) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDependencies", ctx, taskID)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDependencies indicates an expected call of GetDependencies.
func (mr *MockTaskRepositoryMockRecorder) GetDependencies(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDependencies", reflect.TypeOf((*MockTaskRepository)(nil).GetDependencies), ctx, taskID)
}

// List mocks base method.
func (m *MockTaskRepository) List(ctx context.Context, filters task.ListFilters) ([]task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filters)
	ret0, _ := ret[0].([]task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTaskRepositoryMockRecorder) List(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTaskRepository)(nil).List), ctx, filters)
}

// ReleaseInFlightByAgent mocks base method.
func (m *MockTaskRepository) ReleaseInFlightByAgent(ctx context.Context, agentID uuid.UUID) ([]task.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseInFlightByAgent", ctx, agentID)
	ret0, _ := ret[0].([]task.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseInFlightByAgent indicates an expected call of ReleaseInFlightByAgent.
func (mr *MockTaskRepositoryMockRecorder) ReleaseInFlightByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseInFlightByAgent", reflect.TypeOf((*MockTaskRepository)(nil).ReleaseInFlightByAgent), ctx, agentID)
}

// RemoveDependency mocks base method.
func (m *MockTaskRepository) RemoveDependency(ctx context.Context, taskID, dependsOnID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDependency", ctx, taskID, dependsOnID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDependency indicates an expected call of RemoveDependency.
func (mr *MockTaskRepositoryMockRecorder) RemoveDependency(ctx, taskID, dependsOnID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDependency", reflect.TypeOf((*MockTaskRepository)(nil).RemoveDependency), ctx, taskID, dependsOnID)
}

// SetPRUrl mocks base method.
func (m *MockTaskRepository) SetPRUrl(ctx context.Context, id uuid.UUID, prURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPRUrl", ctx, id, prURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPRUrl indicates an expected call of SetPRUrl.
func (mr *MockTaskRepositoryMockRecorder) SetPRUrl(ctx, id, prURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPRUrl", reflect.TypeOf((*MockTaskRepository)(nil).SetPRUrl), ctx, id, prURL)
}

// Unassign mocks base method.
func (m *MockTaskRepository) Unassign(ctx context.Context, taskID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unassign indicates an expected call of Unassign.
func (mr *MockTaskRepositoryMockRecorder) Unassign(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockTaskRepository)(nil).Unassign), ctx, taskID)
}

// UnassignByAgent mocks base method.
func (m *MockTaskRepository) UnassignByAgent(ctx context.Context, agentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignByAgent", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignByAgent indicates an expected call of UnassignByAgent.
func (mr *MockTaskRepositoryMockRecorder) UnassignByAgent(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignByAgent", reflect.TypeOf((*MockTaskRepository)(nil).UnassignByAgent), ctx, agentID)
}

// UpdateStatus mocks base method.
func (m *MockTaskRepository) UpdateStatus(ctx context.Context, id uuid.UUID, from, to task.Status) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, from, to)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTaskRepositoryMockRecorder) UpdateStatus(ctx, id, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTaskRepository)(nil).UpdateStatus), ctx, id, from, to)
}
