// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/notifier/agent.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/notifier/agent.go -destination=internal/mocks/mock_agent_notifier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentNotifier is a mock of AgentNotifier interface.
type MockAgentNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockAgentNotifierMockRecorder
	isgomock struct{}
}

// MockAgentNotifierMockRecorder is the mock recorder for MockAgentNotifier.
type MockAgentNotifierMockRecorder struct {
	mock *MockAgentNotifier
}

// NewMockAgentNotifier creates a new mock instance.
func NewMockAgentNotifier(ctrl *gomock.Controller) *MockAgentNotifier {
	mock := &MockAgentNotifier{ctrl: ctrl}
	mock.recorder = &MockAgentNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentNotifier) EXPECT() *MockAgentNotifierMockRecorder {
	return m.recorder
}

// NotifyAgent mocks base method.
func (m *MockAgentNotifier) NotifyAgent(ctx context.Context, agentID uuid.UUID, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyAgent", ctx, agentID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyAgent indicates an expected call of NotifyAgent.
func (mr *MockAgentNotifierMockRecorder) NotifyAgent(ctx, agentID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyAgent", reflect.TypeOf((*MockAgentNotifier)(nil).NotifyAgent), ctx, agentID, event)
}
