// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/locker/locker.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/locker/locker.go -destination=internal/mocks/mock_locker.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdvisoryLocker is a mock of AdvisoryLocker interface.
type MockAdvisoryLocker struct {
	ctrl     *gomock.Controller
	recorder *MockAdvisoryLockerMockRecorder
	isgomock struct{}
}

// MockAdvisoryLockerMockRecorder is the mock recorder for MockAdvisoryLocker.
type MockAdvisoryLockerMockRecorder struct {
	mock *MockAdvisoryLocker
}

// NewMockAdvisoryLocker creates a new mock instance.
func NewMockAdvisoryLocker(ctrl *gomock.Controller) *MockAdvisoryLocker {
	mock := &MockAdvisoryLocker{ctrl: ctrl}
	mock.recorder = &MockAdvisoryLockerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvisoryLocker) EXPECT() *MockAdvisoryLockerMockRecorder {
	return m.recorder
}

// WithLock mocks base method.
func (m *MockAdvisoryLocker) WithLock(ctx context.Context, key int64, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithLock", ctx, key, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithLock indicates an expected call of WithLock.
func (mr *MockAdvisoryLockerMockRecorder) WithLock(ctx, key, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithLock", reflect.TypeOf((*MockAdvisoryLocker)(nil).WithLock), ctx, key, fn)
}
