// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/notifier/role.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/notifier/role.go -destination=internal/mocks/mock_role_notifier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleNotifier is a mock of RoleNotifier interface.
type MockRoleNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockRoleNotifierMockRecorder
	isgomock struct{}
}

// MockRoleNotifierMockRecorder is the mock recorder for MockRoleNotifier.
type MockRoleNotifierMockRecorder struct {
	mock *MockRoleNotifier
}

// NewMockRoleNotifier creates a new mock instance.
func NewMockRoleNotifier(ctrl *gomock.Controller) *MockRoleNotifier {
	mock := &MockRoleNotifier{ctrl: ctrl}
	mock.recorder = &MockRoleNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleNotifier) EXPECT() *MockRoleNotifierMockRecorder {
	return m.recorder
}

// NotifyProjectRole mocks base method.
func (m *MockRoleNotifier) NotifyProjectRole(ctx context.Context, projectID uuid.UUID, role string, event any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyProjectRole", ctx, projectID, role, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyProjectRole indicates an expected call of NotifyProjectRole.
func (mr *MockRoleNotifierMockRecorder) NotifyProjectRole(ctx, projectID, role, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyProjectRole", reflect.TypeOf((*MockRoleNotifier)(nil).NotifyProjectRole), ctx, projectID, role, event)
}
